### ISSUE TITLE
Release v1.5.0

### ISSUE THREAD

**Issue by GabrielNotman** [arduino-libraries/RTCZero#10]
Can we get the version v1.5.0 submitted to Arduino Library manager.

Currently, the latest version available is v1.4.3.

**Comment by agdl** [comment]
Done!

https://github.com/arduino-libraries/RTCZero/releases/tag/1.5.0

**Comment by GabrielNotman** [comment]
The version number in _libraries.properties_  still needs to be updated to 1.5.0
https://github.com/arduino-libraries/RTCZero/blob/master/library.properties

**Comment by agdl** [comment]
Sorry, forgot to push the commit. Is ok now
