### ISSUE TITLE
setAlarmEpoch has an error

### ISSUE THREAD

**Issue by jamesfahlbusch** [arduino-libraries/RTCZero#26]
From RTCZero.cpp:
```
void RTCZero::setAlarmEpoch(uint32_t ts)
{
  if (_configured) {
    if (ts < EPOCH_TIME_OFF) {
      ts = EPOCH_TIME_OFF;
    }

    time_t t = ts;
    struct tm* tmp = gmtime(&t);

    setAlarmDate(tmp->tm_year - EPOCH_TIME_YEAR_OFF, tmp->tm_mon + 1, tmp->tm_mday);
    setAlarmTime(tmp->tm_hour, tmp->tm_min, tmp->tm_sec);
  }
}
```
`
setAlarmDate(tmp->tm_year - EPOCH_TIME_YEAR_OFF, tmp->tm_mon + 1, tmp->tm_mday);
`
should be:
`
setAlarmDate(tmp->tm_mday, tmp->tm_mon + 1, tmp->tm_year - EPOCH_TIME_YEAR_OFF);
`
because:
`
void RTCZero::setAlarmDate(uint8_t day, uint8_t month, uint8_t year)
`

**Comment by agdl** [comment]
Hi, this has been fixed 13 days ago with https://github.com/arduino-libraries/RTCZero/pull/22. The new library has been release so you should only update it using the library manager
