### ISSUE TITLE
Fox sleep RTC

### ISSUE THREAD

**Issue by Julien8631** [arduino-libraries/RTCZero#34]
Hi,

I have a problem.
sleepRTC doesn't work with MKR FOX 1200.
I want to wakeup the board every minutes to send a SIGFOX message.
The board wake up only once.

Could you help me ?

Thanks

[Fox_sleep_RTC.txt](https://github.com/arduino-libraries/RTCZero/files/1733955/Fox_sleep_RTC.txt)

**Comment by agdl** [comment]
https://github.com/arduino-libraries/ArduinoLowPower you can use the Low Power library to do it
