### ISSUE TITLE
SAMD51 support but unsure if an M4 processor should be included in a M"Zero" library

### ISSUE THREAD

**Issue by ericbaril72** [arduino-libraries/RTCZero#37]
I have code ready but would need to know if it should be added to this library ?
or suggest another one

**Comment by jjunimd** [comment]
Why not?  A name is just a name; many libraries have legacy names that don't fully describe their latest incarnations.  I am **very** interested in trying your M4-compatible code, if possible.
jjuni@stage2innovations.com

**Comment by ericbaril72** [comment]
https://github.com/ericbaril72/RTCZero/tree/SAMD51_E54

**Comment by S2Doc** [comment]
I am trying to use your SAMD52-compatible version of the RTCZero library.  In the src folder is a file called RTCLib.cpp which has #include "RTCLib.h".  Unfortunately there is no RTCLib.h file included.  Can you provide this?

Also, I note that the download contains two copies of RTCZero.cpp.  One is inside the src directory and the other is one level higher.  Should these both be present?

Thank you for your help and for your work for the coding community.
