### ISSUE TITLE
Option to 

### ISSUE THREAD

**Issue by bborncr** [arduino-libraries/RTCZero#7]
By commenting out line 49 (//RTCReset();) in RTCZero.cpp the date/time remains persistent even through firmware updates and manual resets as long as power to the chip is maintained.

So far, it seems to be working just fine.  Is there a potential issue that I should be aware of?

Thanks,

**Comment by GabrielNotman** [comment]
I've created a pull request (#8) which among other additions includes an attempt to preserve the existing clock time. It does it slightly different than your suggestion, however, it should have the same result.

**Comment by agdl** [comment]
@GabrielNotman thank you for your PR. I'm going to tag a new release to include our changes. @bborncr try it and if it is ok for you close the issue please!

**Comment by bborncr** [comment]
We tested the changes and they work fine. You can close the issue.

Thanks!

On Thu, Mar 31, 2016 at 6:15 AM, Arturo Guadalupi <notifications@github.com>
wrote:

> @GabrielNotman <https://github.com/GabrielNotman> thank you for your PR.
> I'm going to tag a new release to include our changes. @bborncr
> <https://github.com/bborncr> try it and if it is ok for you close the
> issue please!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/arduino-libraries/RTCZero/issues/7#issuecomment-203903760>
>



-- 
Bentley Born
CRCibernetica.com
Tel. (506) 2258-5757 x111
Cel. (506) 8896-7539
bentley@ <bentley@gridshield.net>crcibernetica.com
