### ISSUE TITLE
Please add a method for week day getWeekDay()

### ISSUE THREAD

**Issue by balta1980** [arduino-libraries/RTCZero#91]
Please, would you add a new method (maybe getWeekDay()) which return an integer, for example: 0 to 6, where 0: Sunday to 6: Saturday.

Thank you very much.

BJDS

**Comment by per1234** [comment]
Hi @balta1980 . Thanks for taking the time to submit an issue.

I see we have another report about this at https://github.com/arduino-libraries/RTCZero/issues/31.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
